[versions]
agp = "8.3.1"
kotlin = "1.9.0"
coreKtx = "1.10.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2023.08.00"
liveData = "1.4.0"
drawingSupport = "1.1.7"
composeViewModel = "2.6.1"
coroutinesCore = "1.8.0"
coroutinesAndroid = "1.8.0"
appcompat = "1.6.1"
material = "1.10.0"
printSupport = "1.3.0"
#epson = "1.3.0"
#bixolon = "1.3.0"
#gPrinter = "1.3.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "liveData"}
drawingSupport = { group = "com.github.Yiwei099", name="DrawingSupport", version.ref = "drawingSupport" }
viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewModel" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesAndroid"}
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesCore"}
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
epsonPrinter = { group = "com.github.Yiwei099.PrintSupport", name="Epson", version.ref = "printSupport" }
bixolonPrinter = { group = "com.github.Yiwei099.PrintSupport", name="Bixolon", version.ref = "printSupport" }
printer = { group = "com.github.Yiwei099.PrintSupport", name="GPrinter", version.ref = "printSupport" }
printerCommon = { group = "com.github.Yiwei099.PrintSupport", name="libcommon", version.ref = "printSupport" }
#printSupport = { group = "com.github.Yiwei099", name="PrintSupport", version.ref = "printSupport" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

